"""
Regression test for iter 39 — homepage "Batch bozze AI" button must call
`batch-fill-v2` (not the legacy `batch-fill`) so exampleSentences,
deepDive, and videoScript are actually drafted.

Historical bug: PhonemeAdminPage.jsx wired the "Batch bozze AI" button
to `POST /api/admin/phonemes/{id}/batch-fill` which only handles
`mnemonic` + `funFact`. Prof reported "the example sentences are no
longer being generated" — in reality they were NEVER generated by that
button. Iter 38's `_needs_draft` fix was in `batch-fill-v2`, so it
never took effect from the UI.

This test locks in the endpoint contract so a future refactor doesn't
accidentally regress to the legacy endpoint.
"""
import re
from pathlib import Path


FRONTEND_HOMEPAGE = Path(__file__).parent.parent.parent / "frontend" / "src" / "pages" / "PhonemeAdminPage.jsx"


def test_homepage_batch_button_calls_v2_endpoint():
    """The 'Batch bozze AI' button must hit /batch-fill-v2, not legacy /batch-fill."""
    src = FRONTEND_HOMEPAGE.read_text(encoding="utf-8")
    # Strip line-comments before searching so mentions of the legacy endpoint
    # inside a documentation comment (e.g. "…not the legacy /batch-fill…") do
    # not trigger a false positive.
    code_only = "\n".join(
        re.sub(r"//.*$", "", ln) for ln in src.splitlines()
    )
    v2_hits = re.findall(r"/batch-fill-v2", code_only)
    legacy_hits = re.findall(r"/batch-fill(?!-v2)", code_only)
    assert len(v2_hits) >= 1, (
        f"Expected homepage to call /batch-fill-v2, found {len(v2_hits)} hits"
    )
    assert len(legacy_hits) == 0, (
        f"Homepage must NOT call legacy /batch-fill (missing exampleSentences/"
        f"deepDive/videoScript). Found {len(legacy_hits)} legacy hits."
    )


def test_homepage_uses_include_creative_flag():
    """v2 endpoint uses `include_creative` (not the legacy `include_ai`)."""
    src = FRONTEND_HOMEPAGE.read_text(encoding="utf-8")
    # Search in the runBatch handler region only (to avoid false positives)
    # Match the JSON.stringify body sent to batch-fill-v2.
    m = re.search(
        r"batch-fill-v2[^}]+JSON\.stringify\(\s*\{([^}]+)\}\s*\)",
        src, re.DOTALL,
    )
    assert m, "Could not find JSON.stringify payload for batch-fill-v2 call"
    payload = m.group(1)
    assert "include_creative" in payload, (
        f"v2 request body must use `include_creative`, got: {payload.strip()}"
    )
