"""Iteration 38 — FIX A2 (within-window SD stability) + PROBLEMA B
(per-phoneme/per-group plausibility) backend validation.

Tests focused ONLY on the new validation/rejection logic and the diagnostics
shape. NO changes to scoring curves, reference values, CEFR mapping or the
scoring UI are assumed. See /app/backend/routers/phoneme_formants.py.

Fixtures reuse /tmp/vowel.wav (plausible /i/, ~F1 400 F2 2000 F3 2300) and
/tmp/bad.wav (implausible F1~900 F2~900) generated by previous iterations.
If missing, they are synthesized on the fly using a 2-pole resonator glottal
source (16 kHz mono).
"""
from __future__ import annotations

import io
import os
import struct
import wave
from typing import Optional

import numpy as np
import pytest
import requests

BASE_URL = os.environ.get("REACT_APP_BACKEND_URL", "").rstrip("/")
assert BASE_URL, "REACT_APP_BACKEND_URL is required"

ADMIN_USER = "admin"
ADMIN_PASS = "VocalFitness2026!"


# --------------------------------------------------------------------------- #
# WAV synthesis helpers                                                       #
# --------------------------------------------------------------------------- #
def _resonator(x: np.ndarray, f: float, bw: float, sr: int) -> np.ndarray:
    r = float(np.exp(-np.pi * bw / sr))
    theta = 2 * np.pi * f / sr
    a1 = -2 * r * float(np.cos(theta))
    a2 = r * r
    y = np.zeros_like(x)
    y1 = y2 = 0.0
    for i, v in enumerate(x):
        cur = v - a1 * y1 - a2 * y2
        y[i] = cur
        y2 = y1
        y1 = cur
    return y


def _synthesize_vowel_wav(f1: float, f2: float, f3: float,
                          f0: float = 120.0, dur: float = 1.0,
                          sr: int = 16000) -> bytes:
    n = int(sr * dur)
    t = np.arange(n) / sr
    # glottal impulse train
    src = np.zeros(n)
    period = int(round(sr / f0))
    src[::period] = 1.0
    y = _resonator(src, f1, 90.0, sr)
    y = _resonator(y, f2, 110.0, sr)
    y = _resonator(y, f3, 170.0, sr)
    y /= max(1e-9, float(np.max(np.abs(y))))
    y = (0.5 * y * 32767).astype("<i2")
    buf = io.BytesIO()
    with wave.open(buf, "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(sr)
        w.writeframes(y.tobytes())
    return buf.getvalue()


def _load_or_synth(path: str, f1: float, f2: float, f3: float) -> bytes:
    if os.path.exists(path):
        with open(path, "rb") as fh:
            return fh.read()
    return _synthesize_vowel_wav(f1, f2, f3)


# --------------------------------------------------------------------------- #
# Fixtures                                                                    #
# --------------------------------------------------------------------------- #
@pytest.fixture(scope="module")
def token() -> str:
    r = requests.post(
        f"{BASE_URL}/api/auth/login",
        json={"username": ADMIN_USER, "password": ADMIN_PASS},
        timeout=30,
    )
    assert r.status_code == 200, r.text
    body = r.json()
    tok = body.get("token") or body.get("access_token")
    assert tok, f"No token in login response: {body}"
    return tok


@pytest.fixture(scope="module")
def headers(token: str) -> dict:
    return {"Authorization": f"Bearer {token}"}


@pytest.fixture(scope="module", autouse=True)
def ensure_audio_consent(headers):
    # Guarantee we start with consent granted. Individual tests may revoke and
    # re-grant, but the module leaves it granted at teardown.
    _grant(headers, "audio", True)
    _grant(headers, "video", True)
    yield
    _grant(headers, "audio", True)
    _grant(headers, "video", True)


@pytest.fixture(scope="module")
def plausible_i_wav() -> bytes:
    # Deterministic synthetic /i/ AmE-men whose extracted formants land inside
    # the /i/ plausibility range with margin (F1≈388, F2≈1922, F3≈2411). NOTE:
    # do NOT load a leftover /tmp file — that made the fixture non-reproducible.
    return _synthesize_vowel_wav(300.0, 2400.0, 3400.0)


@pytest.fixture(scope="module")
def implausible_wav() -> bytes:
    # Deterministic off-target signal (F1 1000 / F2 900) → implausible for /i/.
    return _synthesize_vowel_wav(1000.0, 900.0, 2100.0)


# --------------------------------------------------------------------------- #
# Small HTTP helpers                                                          #
# --------------------------------------------------------------------------- #
def _grant(headers: dict, kind: str, granted: bool):
    r = requests.post(
        f"{BASE_URL}/api/phonemes/consent",
        json={"kind": kind, "granted": granted},
        headers=headers, timeout=30,
    )
    assert r.status_code == 200, r.text
    return r.json()


def _analyze(headers: dict, wav: bytes, phoneme_ipa: str, dialect: str,
             target_kind: str = "phoneme",
             reference_url: str = "") -> requests.Response:
    files = {"file": ("v.wav", wav, "audio/wav")}
    data = {
        "phoneme_ipa": phoneme_ipa,
        "dialect": dialect,
        "target_kind": target_kind,
        "reference_url": reference_url,
    }
    return requests.post(
        f"{BASE_URL}/api/phonemes/analyze-formants",
        headers=headers, files=files, data=data, timeout=60,
    )


# --------------------------------------------------------------------------- #
# 1) Auth + consent gate                                                       #
# --------------------------------------------------------------------------- #
class TestAuthConsentGate:
    def test_403_without_audio_consent(self, headers, plausible_i_wav):
        _grant(headers, "audio", False)
        r = _analyze(headers, plausible_i_wav, "i", "AmE")
        assert r.status_code == 403, r.text
        detail = (r.json().get("detail") or "").lower()
        assert "consenso" in detail or "audio" in detail, r.text

    def test_200_after_granting_consent(self, headers, plausible_i_wav):
        _grant(headers, "audio", True)
        r = _analyze(headers, plausible_i_wav, "i", "AmE")
        assert r.status_code == 200, r.text


# --------------------------------------------------------------------------- #
# 2) Plausible + stable case: 200 with full diagnostics                        #
# --------------------------------------------------------------------------- #
class TestPlausibleStable200:
    def test_full_success_shape(self, headers, plausible_i_wav):
        _grant(headers, "audio", True)
        r = _analyze(headers, plausible_i_wav, "i", "AmE")
        assert r.status_code == 200, r.text
        body = r.json()

        # Top-level scoring shape unchanged
        assert isinstance(body.get("composite_score"), (int, float))
        cefr = body.get("cefr") or {}
        assert cefr.get("band")
        assert cefr.get("label")
        per_formant = body.get("per_formant") or []
        assert per_formant, "per_formant list must be non-empty"
        for pf in per_formant:
            assert pf["name"] in {"F1", "F2", "F3"}
            assert isinstance(pf.get("measured"), (int, float))
            assert isinstance(pf.get("reference"), (int, float))
            assert isinstance(pf.get("score"), (int, float))

        # Dispersion source ties to formant_references.sd_source ('estimated_pooled')
        assert body.get("dispersion_source") == "estimated", (
            f"dispersion_source must be 'estimated' when SDs are pooled "
            f"estimates, got: {body.get('dispersion_source')}"
        )

        # Diagnostics shape
        d = body.get("diagnostics") or {}
        assert d, f"diagnostics missing: {body}"
        assert d.get("reliable") is True

        # nucleus_sd_hz — present, has at least one formant
        n_sd = d.get("nucleus_sd_hz") or {}
        assert n_sd, f"nucleus_sd_hz missing/empty: {d}"
        for k, v in n_sd.items():
            assert k in {"F1", "F2", "F3"}
            assert isinstance(v, (int, float))

        # nucleus_sd_thresholds_hz — exact FIX A2 values
        thr = d.get("nucleus_sd_thresholds_hz") or {}
        assert thr == {"F1": 25.0, "F2": 50.0, "F3": 70.0}, thr

        # plausibility_range_hz — per formant with ref/sd_used/sd_source/min/max
        pr = d.get("plausibility_range_hz") or {}
        assert set(pr.keys()) & {"F1", "F2", "F3"}, pr
        for name, rng in pr.items():
            for key in ("ref", "sd_used", "sd_source", "min", "max"):
                assert key in rng, f"{name} range missing {key}: {rng}"
            assert rng["min"] < rng["max"]
            # sd_source must be 'estimated_pooled' for Hillenbrand dataset rows
            assert rng["sd_source"] == "estimated_pooled", (
                f"{name}.sd_source expected 'estimated_pooled', got "
                f"{rng['sd_source']!r}"
            )

    def test_within_window_sd_below_thresholds(self, headers, plausible_i_wav):
        _grant(headers, "audio", True)
        r = _analyze(headers, plausible_i_wav, "i", "AmE")
        assert r.status_code == 200, r.text
        d = r.json()["diagnostics"]
        thr = d["nucleus_sd_thresholds_hz"]
        n_sd = d["nucleus_sd_hz"]
        for k, sd in n_sd.items():
            assert sd <= thr[k], (
                f"FIX A2 assertion: chosen window {k}_sd={sd} exceeded "
                f"threshold={thr[k]} — window should have been rejected."
            )


# --------------------------------------------------------------------------- #
# 3) Implausible case: 422 with structured detail object                      #
# --------------------------------------------------------------------------- #
class TestImplausibleReturns422StructuredDetail:
    def test_off_target_signal_as_i_returns_422(self, headers, implausible_wav):
        # /bad.wav/ is F1~1000 F2~900 — nowhere near /i/ AmE (F1 342 F2 2322).
        _grant(headers, "audio", True)
        r = _analyze(headers, implausible_wav, "i", "AmE")
        assert r.status_code == 422, r.text
        body = r.json()
        detail = body.get("detail")
        assert isinstance(detail, dict), (
            f"422 detail must be a structured OBJECT (not a string). Got: "
            f"{type(detail).__name__} — {detail!r}"
        )

        # required keys on the detail object
        for k in ("message", "reason", "offenders", "expert"):
            assert k in detail, f"detail.{k} missing: {detail}"

        # actionable Italian message (no jargon)
        msg = (detail.get("message") or "").lower()
        assert "affidabile" in msg or "silenzioso" in msg or "fermo" in msg, (
            f"detail.message must be actionable Italian, got: {msg!r}"
        )

        # reason MUST be 'implausible' for this off-target signal
        assert detail.get("reason") == "implausible", (
            f"reason must be 'implausible' for off-target F1~1000 measured "
            f"as /i/, got: {detail.get('reason')!r}"
        )

        # expert.attempts must show ALL 3 ceilings were retried, each plausible=False
        expert = detail.get("expert") or {}
        attempts = expert.get("attempts") or []
        assert len(attempts) >= 3, (
            f"expert.attempts must show 3 LPC-ceiling retries "
            f"(5500/5000/4500), got: {attempts}"
        )
        ceilings_seen = {a.get("ceiling_hz") for a in attempts
                        if isinstance(a, dict)}
        assert {5500, 5000, 4500}.issubset(ceilings_seen), (
            f"expert.attempts must cover 5500/5000/4500 Hz, got ceilings: "
            f"{ceilings_seen}"
        )
        # Every attempt with a measurement must be marked plausible: False
        for a in attempts:
            if isinstance(a, dict) and a.get("F1") is not None:
                assert a.get("plausible") is False, (
                    f"attempt at ceiling={a.get('ceiling_hz')} should be "
                    f"plausible=False for this off-target signal, got: {a}"
                )

        # expert.plausibility_range_hz must be present
        pr = expert.get("plausibility_range_hz") or {}
        assert pr, f"expert.plausibility_range_hz missing: {expert}"
        for name, rng in pr.items():
            for key in ("ref", "sd_used", "sd_source", "min", "max"):
                assert key in rng, f"{name} range missing {key}: {rng}"

        # No composite_score smuggled on 422
        assert "composite_score" not in body

    def test_422_expert_reports_measured_f1_beyond_range(
        self, headers, implausible_wav
    ):
        """expert.attempts must show measured F1 values that are outside the
        plausibility range for /i/ AmE (i.e. > 465 Hz)."""
        _grant(headers, "audio", True)
        r = _analyze(headers, implausible_wav, "i", "AmE")
        assert r.status_code == 422, r.text
        expert = r.json()["detail"]["expert"]
        f1_max = expert["plausibility_range_hz"]["F1"]["max"]
        # At least one attempt should have F1 > f1_max, proving the rejection
        # is driven by the per-phoneme range (not a global 900 Hz cutoff).
        offenders = [a for a in expert["attempts"]
                     if isinstance(a, dict) and a.get("F1")
                     and a["F1"] > f1_max]
        assert offenders, (
            f"No attempt shows F1 above the per-phoneme plausibility ceiling "
            f"F1.max={f1_max}: attempts={expert['attempts']}"
        )


# --------------------------------------------------------------------------- #
# 4) Per-phoneme (NOT global) plausibility — core of PROBLEMA B               #
# --------------------------------------------------------------------------- #
class TestPerPhonemePlausibilityRange:
    def test_i_AmE_men_F1_range_is_narrow(self, headers, plausible_i_wav):
        """/i/ AmE men F1 range must be roughly 219..465 Hz (± 3 × pooled
        SD around Hillenbrand mean 342 Hz). This proves plausibility is
        per-phoneme, NOT the old global F1>900 rule."""
        _grant(headers, "audio", True)
        r = _analyze(headers, plausible_i_wav, "i", "AmE")
        assert r.status_code == 200, r.text
        pr = r.json()["diagnostics"]["plausibility_range_hz"]
        f1_min = pr["F1"]["min"]
        f1_max = pr["F1"]["max"]
        # Hillenbrand men mean 342, pooled SD 12% → ~41, ±3σ → ~219..465
        assert 200 <= f1_min <= 240, f"F1 min expected ~219, got {f1_min}"
        assert 450 <= f1_max <= 490, f"F1 max expected ~465, got {f1_max}"
        assert pr["F1"]["ref"] == 342

    def test_i_AmE_rejects_f1_900(self, headers):
        """A synthesized signal with F1~1000 F2~900 (well within the OLD
        global F1<900 tolerance if we bumped F1 to say 850 — but far from
        /i/) must be rejected because the per-phoneme range for /i/ AmE men
        is 219..465 Hz."""
        _grant(headers, "audio", True)
        wav = _synthesize_vowel_wav(1000.0, 900.0, 2100.0)
        r = _analyze(headers, wav, "i", "AmE")
        assert r.status_code == 422, (
            f"F1~1000 must be rejected as /i/ (per-phoneme range 219..465). "
            f"got {r.status_code}: {r.text[:400]}"
        )
        assert r.json()["detail"]["reason"] == "implausible"

    def test_different_phoneme_has_different_range(self, headers,
                                                    plausible_i_wav):
        """Range for /ɑ/ AmE (open back vowel, F1 mean ~768) must be much
        higher than for /i/ (F1 mean ~342). Even if we cannot get a 200 for
        an /ɑ/ recording from a synthesized /i/ WAV, the 422 detail STILL
        exposes the /ɑ/ plausibility_range_hz — which must differ."""
        _grant(headers, "audio", True)
        # /i/ AmE range
        r_i = _analyze(headers, plausible_i_wav, "i", "AmE")
        assert r_i.status_code == 200, r_i.text
        rng_i = r_i.json()["diagnostics"]["plausibility_range_hz"]["F1"]
        # /ɑ/ AmE range: whether it succeeds or 422s, we can extract the range.
        r_a = _analyze(headers, plausible_i_wav, "ɑ", "AmE")
        assert r_a.status_code in (200, 422), r_a.text
        if r_a.status_code == 200:
            rng_a = r_a.json()["diagnostics"]["plausibility_range_hz"]["F1"]
        else:
            rng_a = r_a.json()["detail"]["expert"]["plausibility_range_hz"]["F1"]
        assert rng_a["ref"] != rng_i["ref"], (
            f"Expected different reference means per phoneme: /i/={rng_i}, "
            f"/ɑ/={rng_a}"
        )
        assert rng_a["ref"] > rng_i["ref"], (
            f"/ɑ/ F1 mean should be higher than /i/ F1 mean, got "
            f"/ɑ/={rng_a['ref']} /i/={rng_i['ref']}"
        )


# --------------------------------------------------------------------------- #
# 5) Consent endpoints — audio/video independent                              #
# --------------------------------------------------------------------------- #
class TestConsentEndpointsIndependent:
    def test_get_consent(self, headers):
        r = requests.get(f"{BASE_URL}/api/phonemes/consent", headers=headers,
                         timeout=30)
        assert r.status_code == 200, r.text
        body = r.json()
        assert "audio_granted" in body
        assert "video_granted" in body
        assert isinstance(body["audio_granted"], bool)
        assert isinstance(body["video_granted"], bool)

    def test_set_audio_does_not_affect_video(self, headers):
        # Grant video, revoke audio → video must remain granted
        _grant(headers, "video", True)
        _grant(headers, "audio", False)
        r = requests.get(f"{BASE_URL}/api/phonemes/consent", headers=headers,
                         timeout=30)
        body = r.json()
        assert body["audio_granted"] is False
        assert body["video_granted"] is True
        # And vice versa: grant audio, revoke video → audio remains granted
        _grant(headers, "audio", True)
        _grant(headers, "video", False)
        r = requests.get(f"{BASE_URL}/api/phonemes/consent", headers=headers,
                         timeout=30)
        body = r.json()
        assert body["audio_granted"] is True
        assert body["video_granted"] is False
        # Restore
        _grant(headers, "video", True)

    def test_invalid_kind_400(self, headers):
        r = requests.post(
            f"{BASE_URL}/api/phonemes/consent",
            json={"kind": "notakind", "granted": True},
            headers=headers, timeout=30,
        )
        assert r.status_code == 400, r.text


# --------------------------------------------------------------------------- #
# 6) sd_source in formant_references — drives dispersion_source                #
# --------------------------------------------------------------------------- #
class TestSdSourceInReferences:
    def test_estimated_pooled_flag_in_diagnostics(self, headers,
                                                  plausible_i_wav):
        """Every plausibility range for an /i/-AmE 200 response must show
        sd_source='estimated_pooled', proving the flag from the DB row
        propagates into the diagnostics envelope."""
        _grant(headers, "audio", True)
        r = _analyze(headers, plausible_i_wav, "i", "AmE")
        assert r.status_code == 200, r.text
        pr = r.json()["diagnostics"]["plausibility_range_hz"]
        for name, rng in pr.items():
            assert rng["sd_source"] == "estimated_pooled", (
                f"{name}.sd_source must be 'estimated_pooled' (was "
                f"{rng['sd_source']!r})"
            )

    def test_dispersion_source_estimated_for_dataset(self, headers,
                                                    plausible_i_wav):
        _grant(headers, "audio", True)
        r = _analyze(headers, plausible_i_wav, "i", "AmE")
        assert r.status_code == 200, r.text
        body = r.json()
        assert body["reference_source"] == "dataset"
        assert body["dispersion_source"] == "estimated"
